# problem set Explore 2 variables

# clear the workspace
rm(list = ls())

# Q1 : price vs x.
```{r}
# In this problem set, you'll continue
# to explore the diamonds data set.

# Your first task is to create a
# scatterplot of price vs x.
# using the ggplot syntax.

# This assignment is not graded and
# will be marked as correct when you submit.

# ENTER YOUR CODE BELOW THIS LINE
# ===========================================
library(ggplot2)
diamonds
summary(diamonds)

ggplot(aes(x=price, y=x), data = diamonds) + geom_line()

```

# Q2 : findings price vs x.
in general as price increases x value increases
but there are few outliers 

# Q3 : Correlations
```{r}

cor.test(diamonds$price, diamonds$x)

cor.test(diamonds$price, diamonds$y)

cor.test(diamonds$price, diamonds$z)

```

# Q4 :  price vs depth
```{r}
# Create a simple scatter plot of price vs depth.

# This assignment is not graded and
# will be marked as correct when you submit.

# ENTER YOUR CODE BELOW THIS LINE
#==================================================

ggplot(aes(x=price, y= depth), data=diamonds) + geom_point(alpha = 1)  + scale_x_continuous(breaks = 10)

```


# Q6 : typical depth range
60-63


# Q7 : cor b/w depth price
```{r}

cor.test(diamonds$depth, diamonds$price)

```

as the correlation is weak we can't use depth to predict the price of the diamond

# Q9 : price vs carat
```{r}

# Create a scatterplot of price vs carat
# and omit the top 1% of price and carat
# values.

# This assignment is not graded and
# will be marked as correct when you submit.

# ENTER YOUR CODE BELOW THIS LINE
# ========================================
ggplot(data = diamonds,aes(x = carat, y = price)) + 
  xlim(0,quantile(diamonds$carat,0.99)) +
  ylim(0,quantile(diamonds$price,0.99)) +
  geom_point()



```

# Q10 : 
```{r}
# Create a scatterplot of price vs. volume (x * y * z).
# This is a very rough approximation for a diamond's volume.

# Create a new variable for volume in the diamonds data frame.
# This will be useful in a later exercise.

# Don't make any adjustments to the plot just yet.

# This assignment is not graded and
# will be marked as correct when you submit.

# ENTER YOUR CODE BELOW THIS LINE
# =================================================================
diamonds$volume <- diamonds$x * diamonds$y * diamonds$z

ggplot(aes(price, volume), data = diamonds) + geom_point()

```

```{r}
install.packages(plyr)
library(plyr)
detach("package:plyr", unload=TRUE)

count(diamonds$volume == 0)

cor.test(diamonds$price, diamonds$volume)
?with

with(subset(diamonds , diamonds$volume!=0 & diamonds$volume < 800), cor.test(price, volume))

```

# Q12 : 
```{r}
# Subset the data to exclude diamonds with a volume
# greater than or equal to 800. Also, exclude diamonds
# with a volume of 0. Adjust the transparency of the
# points and add a linear model to the plot. (See the
# Instructor Notes or look up the documentation of
# geom_smooth() for more details about smoothers.)

# We encourage you to think about this next question and
# to post your thoughts in the discussion section.

# Do you think this would be a useful model to estimate
# the price of diamonds? Why or why not?

# This assignment is not graded and
# will be marked as correct when you submit.

# ENTER YOUR CODE BELOW THIS LINE
# ========================================


ggplot(aes(price, volume), data = subset(diamonds , diamonds$volume!=0 & diamonds$volume < 800)) + geom_point() + geom_smooth()


```


# Q13 : 
```{r}
# Use the function dplyr package
# to create a new data frame containing
# info on diamonds by clarity.

# Name the data frame diamondsByClarity

# The data frame should contain the following
# variables in this order.

#       (1) mean_price
#       (2) median_price
#       (3) min_price
#       (4) max_price
#       (5) n

# where n is the number of diamonds in each
# level of clarity.

# This assignment WILL BE automatically
# graded!

# DO NOT ALTER THE NEXT THREE LINES OF CODE.
# ======================================================
suppressMessages(library(ggplot2))
suppressMessages(library(dplyr))
data(diamonds)

# ENTER YOUR CODE BELOW THIS LINE
# ======================================================
# age_groups <- group_by(pf, age_with_months)
# pf.fc_by_age_months <- summarise(age_groups,
#                          friend_count_mean = mean(friend_count),
#                          friend_count_median = median(friend_count),
#                          n = n())

# pf.fc_by_age_months <- arrange(pf.fc_by_age_months, age_with_months)
# head(pf.fc_by_age_months)

# detach("package:plyr", unload=TRUE) 

diamond_groups <- group_by(diamonds, clarity)

diamonds.diamondsByClarity <- summarise(diamond_groups,
                          mean_price = mean(price),
                          median_price = median(price),
                          min_price = min(price),
                          max_price = max(price),
                          n = n())

diamondsByClarity <- arrange(diamonds.diamondsByClarity, clarity)
head(diamondsByClarity)

```

# Q14 : 
```{r}

# We’ve created summary data frames with the mean price
# by clarity and color. You can run the code in R to
# verify what data is in the variables diamonds_mp_by_clarity
# and diamonds_mp_by_color.

# Your task is to write additional code to create two bar plots
# on one output image using the grid.arrange() function from the package
# gridExtra.

# This assignment is not graded and
# will be marked as correct when you submit.

# See the Instructor Notes for more info on bar charts
# and for a hint on this task.

# DO NOT DELETE THE LINES OF CODE BELOW
# ===================================================================
data(diamonds)
library(dplyr)

diamonds_by_clarity <- group_by(diamonds, clarity)
diamonds_mp_by_clarity <- summarise(diamonds_by_clarity, mean_price = mean(price))

diamonds_by_color <- group_by(diamonds, color)
diamonds_mp_by_color <- summarise(diamonds_by_color, mean_price = mean(price))

# ENTER YOUR CODE BELOW THIS LINE
# ===================================================================

p1<-barplot(diamonds_mp_by_clarity$mean_price)
p2<-barplot(diamonds_mp_by_color$mean_price)

library(gridExtra)
grid.arrange(p1,p2, ncol = 1)



p1<-ggplot(aes(x=diamonds_mp_by_clarity$mean_price),data=diamonds_mp_by_clarity)  + geom_bar()
p2<-ggplot(aes(x=diamonds_mp_by_color$mean_price),data= diamonds_mp_by_color) + geom_bar()

library(gridExtra)
grid.arrange(p1,p2, ncol = 1)

```



# Q16 : 
```{r}
# The Gapminder website contains over 500 data sets with information about
# the world's population. Your task is to continue the investigation you did at the
# end of Problem Set 3 or you can start fresh and choose a different
# data set from Gapminder.

# If you’re feeling adventurous or want to try some data munging see if you can
# find a data set or scrape one from the web.

# In your investigation, examine pairs of variable and create 2-5 plots that make
# use of the techniques from Lesson 4.

# You can find a link to the Gapminder website in the Instructor Notes.

# Once you've completed your investigation, create a post in the discussions that includes:
#       1. the variable(s) you investigated, your observations, and any summary statistics
#       2. snippets of code that created the plots
#       3. links to the images of your plots

# Copy and paste all of the code that you used for
# your investigation, and submit it when you are ready.
# ====================================================================

agcl <- read.csv('agriculture land.csv')

View(agcl)

summary(agcl)

dim(agcl)

ind1 <- as.data.frame(t(subset(agcl, agcl$Agricultural.land....of.land.area.=='India')))
pak1 <- as.data.frame(t(subset(agcl, agcl$Agricultural.land....of.land.area.=='Pakistan')))
bang1 <- as.data.frame(t(subset(agcl, agcl$Agricultural.land....of.land.area.=='Bangladesh')))
china1 <- as.data.frame(t(subset(agcl, agcl$Agricultural.land....of.land.area.=='China')))
sl1 <- as.data.frame(t(subset(agcl, agcl$Agricultural.land....of.land.area.=='Sri Lanka')))

asia1 <- as.data.frame(c(ind1, pak1, bang1, china1, sl1))


View(asia1)

dim(asia1)

library(ggplot2)

ggplot(aes(x=asia1$X87, y=asia1$X147), data = asia1) + geom_point()

ggplot(aes(x=agcl$X1960, y=agcl$Agricultural.land....of.land.area.),data=agcl) + geom_point() 

```